//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XentuCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XentuCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About Xentu Creator.
        /// </summary>
        public static string CommandAbout {
            get {
                return ResourceManager.GetString("CommandAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string CommandClose {
            get {
                return ResourceManager.GetString("CommandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Debug Settings....
        /// </summary>
        public static string CommandDebugSettings {
            get {
                return ResourceManager.GetString("CommandDebugSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string CommandExit {
            get {
                return ResourceManager.GetString("CommandExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game P_roperties.
        /// </summary>
        public static string CommandGameProperties {
            get {
                return ResourceManager.GetString("CommandGameProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Game.
        /// </summary>
        public static string CommandNewGame {
            get {
                return ResourceManager.GetString("CommandNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Existing....
        /// </summary>
        public static string CommandOpenExisting {
            get {
                return ResourceManager.GetString("CommandOpenExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string CommandOptions {
            get {
                return ResourceManager.GetString("CommandOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Debugging.
        /// </summary>
        public static string CommandPlay {
            get {
                return ResourceManager.GetString("CommandPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Without Debugging.
        /// </summary>
        public static string CommandPlayRelease {
            get {
                return ResourceManager.GetString("CommandPlayRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Publish....
        /// </summary>
        public static string CommandPublish {
            get {
                return ResourceManager.GetString("CommandPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CommandSave {
            get {
                return ResourceManager.GetString("CommandSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _All.
        /// </summary>
        public static string CommandSaveAll {
            get {
                return ResourceManager.GetString("CommandSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle _Fullscreen.
        /// </summary>
        public static string CommandToggleFullscreen {
            get {
                return ResourceManager.GetString("CommandToggleFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string LabelRecentProjects {
            get {
                return ResourceManager.GetString("LabelRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LabelWelcome {
            get {
                return ResourceManager.GetString("LabelWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Run.
        /// </summary>
        public static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
    }
}
